import React from 'react';
import Feature from './Feature';

const featuresData = [
  {
    icon: '/calculator.svg',
    title: 'Proximity Scoring',
    description:
      'Our app calculates the distance from real estate properties to essential facilities like hospitals, bus stops, subways, schools, and more. This enables a comprehensive understanding of the property’s accessibility and value.',
  },
  {
    icon: '/clock-check.svg',
    title: 'Real-Time Data Scraping',
    description:
      'Using cutting-edge technology, the app scrapes the most up-to-date information from various sources, such as current market trends, neighborhood growth rates, and demographic shifts. This ensures you have access to the freshest data available for making informed decisions.',
  },
  {
    icon: '/chart-breakout-square.svg',
    title: 'Investment Viability Predictions',
    description:
      'Beyond raw data, our app leverages predictive algorithms to forecast whether a property is a good investment. By analyzing trends, future developments, and local demand, the app provides forecasts that can guide long-term investment strategies.',
  },
  {
    icon: '/pie-chart-02.svg',
    title: 'Market-Driven Insights',
    description:
      "Whether you're a marketer looking for high-potential areas, an investor seeking the best opportunities, or a real estate agency or bank assessing risk, the data generated by the app helps target key properties and forecast market trends.",
  },
];

const Features: React.FC = () => (
  <section className="flex overflow-hidden flex-col items-center self-center py-24 w-full bg-[color:var(--sds-color-background-default-default)] opacity-[var(--sds-size-stroke-border)] max-md:max-w-full">
    <div className="flex flex-col px-8 max-w-full w-[1280px] max-md:px-5">
      <div className="flex flex-col items-start w-full max-md:max-w-full">
        <div className="flex flex-col max-w-full w-[768px]">
          <div className="flex flex-col w-full font-semibold max-md:max-w-full">
            <span className="text-base text-blue-700 opacity-[var(--sds-size-stroke-border)] max-md:max-w-full">
              Features
            </span>
            <h2 className="mt-3 text-4xl tracking-tighter leading-none text-gray-900 opacity-[var(--sds-size-stroke-border)] max-md:max-w-full">
              Beautiful analytics to grow smarter
            </h2>
          </div>
          <p className="mt-5 text-xl leading-8 opacity-[var(--sds-size-stroke-border)] text-slate-600 max-md:max-w-full">
            Powerful, self-serve product and growth analytics to help you
            convert, engage, and retain more users. Trusted by over 4,000
            startups.
          </p>
        </div>
      </div>
    </div>
    <div className="flex flex-col px-8 mt-16 max-w-full w-[1280px] max-md:px-5 max-md:mt-10">
      <div className="flex flex-wrap gap-6 items-start w-full max-md:max-w-full">
        {featuresData.map((feature, index) => (
          <Feature key={index} {...feature} />
        ))}
      </div>
    </div>
  </section>
);

export default Features;
